python run_summarization.py \
        --model_name_or_path google/mt5-small \
        --do_train \
        --do_eval \
        --do_predict \
        --train_file "${1}" \
        --validation_file "${2}" \
        --test_file "${2}" \
        --output_file_name "${3}" \
        --source_prefix "summarize: " \
        --output_dir "./tst-summarization" \
        --overwrite_output_dir \
        --per_device_train_batch_size=4 \
        --gradient_accumulation_steps=4 \
        --per_device_eval_batch_size=4 \
        --predict_with_generate \
        --adafactor \
        --learning_rate 5e-4 \
        --text_column "maintext" \
        --summary_column "title"